export interface CustomSVGProps {
  width: string;
  height: string;
  color: string;
}

export * from './Bookmark';
export * from './BookmarkOutline';
export * from './CheckmarkOutline';
export * from './CloseOutline';
export * from './CollapseOutline';
export * from './ColorPaletteOutline';
export * from './Downward';
export * from './ExpandOutline';
export * from './ForwardOutline';
export * from './Heart';
export * from './HeartOutline';
export * from './Home';
export * from './HomeOutline';
export * from './Layer';
export * from './MaxmizeOutline';
export * from './Person';
export * from './PersonOutline';
export * from './Share';
export * from './ShareOutline';
export * from './ShoppingCart';
export * from './ShoppingCartOutline';
export * from './TablerPhotoSensor';
export * from './TablerPhotoSensorOutline';
export * from './UpwardOutline';
export * from './CancelIcon';
export * from './Warnning';
export * from './Trash';
export * from './TextIcon';
export * from './Pencil';
export * from './Penwidth';
export * from './LeftArrow';
export * from './RightArrow';
export * from './Eraser';
export * from './CircleDrawing';
export * from './ThumbsUp';
export * from './ThumbsDown';
export * from './BackwardOutline';
export * from './Kakao';
export * from './Question';
export * from './PlusOutline';
export * from './FilterIconFill';
